version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - echo Build started on `date`
      - time=$(date +%s)
      - mkdir -p output/${time}
      - cp admin_dags/* output/${time}
      - find ./
